# template.yml
# Use this as a starting point for your own Buildkite pipeline

name: "Concurrency Group Example"
description: "A Buildkite pipeline demonstrating concurrency groups and gates to control job flow."

steps:
  - label: ":large_green_square: OPEN GATE: Tests"
    key: "start-tests"
    concurrency_group: "tests"
    command: echo "Opening Test gate"

  - wait

  - label: "Tests"
    key: "tests"
    concurrency_group: "tests"
    parallelism: 5
    depends_on: ["start-tests"]
    command: echo "run-tests.sh"

  - label: ":large_red_square: CLOSE GATE: Tests"
    key: "end-tests"
    concurrency_group: "tests"
    depends_on: ["tests"]
    command: echo "Closed the Test gate"
